### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [3]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [123]:
#help(np.array)
#help(car)

#dir on car lists all methods and attributes that can be used e.g min, max, ndim etc. which dir on np.array didn't list.
dir(np.array)
dir(car)

#display(df)
#df.head()
#df.tail()


['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [14]:
print("car datatype: ", car.dtype)
print("mpg datatype: ", mpg.dtype)
print("horsepower datatype: ", horsepower.dtype)
print("origin datatype", origin.dtype)

car datatype:  object
mpg datatype:  float64
horsepower datatype:  float64
origin datatype object


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
#This is called as giving an alias. It is to refer the same instance with a different name.

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [18]:
#Print dimension of the arrays - car, mpg,cylinders
print("Dimension of car: ", car.ndim)
print("Dimension of mpg: ", mpg.ndim)
print("Dimension of cylinders: ", cylinders.ndim)

Dimension of car:  1
Dimension of mpg:  1
Dimension of cylinders:  1


5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [124]:
#print mpg array
print(mpg)

#multiply mpg array by 12 i.e multiply each element of array with 12
print(mpg * 12)
#print(np.multiply(mpg,12))

#divide mpg array by 3 i.e divide each element of array with 3
print(mpg / 3)
#print(np.divide(mpg,3))

#raise the mpg array to the power of 4 i.e raise each element of array to the power of 4
print(mpg ** 4)
#print(np.power(mpg,4))

#take the square root of the mpg array i.e take square root of each element of the array.
print(np.sqrt(mpg))

[18.  15.  18.  16.  17.  15.  14.  14.  14.  15.   0.   0.   0.   0.
  0.  15.  14.   0.  15.  14.  24.  22.  18.  21.  27.  26.  25.  24.
 25.  26.  21.  10.  10.  11.   9.  27.  28.  25.  25.   0.  19.  16.
 17.  19.  18.  14.  14.  14.  14.  12.  13.  13.  18.  22.  19.  18.
 23.  28.  30.  30.  31.  35.  27.  26.  24.  25.  23.  20.  21.  13.
 14.  15.  14.  17.  11.  13.  12.  13.  19.  15.  13.  13.  14.  18.
 22.  21.  26.  22.  28.  23.  28.  27.  13.  14.  13.  14.  15.  12.
 13.  13.  14.  13.  12.  13.  18.  16.  18.  18.  23.  26.  11.  12.
 13.  12.  18.  20.  21.  22.  18.  19.  21.  26.  15.  16.  29.  24.
 20.  19.  15.  24.  20.  11.  20.  21.  19.  15.  31.  26.  32.  25.
 16.  16.  18.  16.  13.  14.  14.  14.  29.  26.  26.  31.  32.  28.
 24.  26.  24.  26.  31.  19.  18.  15.  15.  16.  15.  16.  14.  17.
 16.  15.  18.  21.  20.  13.  29.  23.  20.  23.  24.  25.  24.  18.
 29.  19.  23.  23.  22.  25.  33.  28.  25.  25.  26.  27.  17.5 16.
 15.5 14.5 22.  22. 

[ 104976.       50625.      104976.       65536.       83521.
   50625.       38416.       38416.       38416.       50625.
       0.           0.           0.           0.           0.
   50625.       38416.           0.       50625.       38416.
  331776.      234256.      104976.      194481.      531441.
  456976.      390625.      331776.      390625.      456976.
  194481.       10000.       10000.       14641.        6561.
  531441.      614656.      390625.      390625.           0.
  130321.       65536.       83521.      130321.      104976.
   38416.       38416.       38416.       38416.       20736.
   28561.       28561.      104976.      234256.      130321.
  104976.      279841.      614656.      810000.      810000.
  923521.     1500625.      531441.      456976.      331776.
  390625.      279841.      160000.      194481.       28561.
   38416.       50625.       38416.       83521.       14641.
   28561.       20736.       28561.      130321.       50625.
   28561

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [125]:
import statistics as stats
#find sum of horsepower array
print("Sum of horsepower: ", np.sum(horsepower))

#find min of horsepower array
print("min of horsepower: ",np.min(horsepower))

#find max of horsepower array
print("max of horsepower: ",np.max(horsepower))

#find median of horsepower array
print("median of horsepower: ",np.median(horsepower))

#find mode of horsepower
print("mode of horsepower: ",stats.mode(horsepower))

Sum of horsepower:  42033.0
min of horsepower:  0.0
max of horsepower:  230.0
median of horsepower:  93.5
mode of horsepower:  150.0


7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [44]:
#select the subset of acceleration
#print(acceleration)
print("Only first 5 elements :" , acceleration[0:5])
print("Every other element : \n", acceleration[::2])

Only first 5 elements : [12.  11.5 11.  12.  10.5]
Every other element : 
 [12.  11.  10.5  9.  10.  17.5 11.  11.   8.   9.5 15.  15.5 14.5 17.5
 17.5 15.  15.  18.5 15.5 19.  13.  15.5 15.5 11.5 13.  12.  13.5 15.
 14.  19.5 19.  19.  15.5 23.5 16.5 12.  13.  11.  13.5 13.5 14.  14.
 18.  18.  17.  15.  13.  13.  12.5 12.  14.5 11.  16.5 16.  16.  14.
 13.  15.  19.5 13.5 14.  13.  19.5 14.  11.  13.5 16.5 16.  19.  21.
 17.  16.5 14.5 16.  16.5 14.5 19.  15.5 15.  16.  16.  19.5 14.  13.5
 18.5 19.  13.5 16.  16.  13.5 17.  14.  15.  14.5 17.5 16.9 17.7 13.
 13.9 15.4 17.6 22.2 14.2 17.7 16.2 12.2 16.4 15.7 21.9 16.7 12.  14.
 14.8 15.5 12.5 13.7 16.4 17.7 11.1 12.2 14.5 18.2 17.  16.4 14.5 13.5
 14.4 18.6 15.5 12.8 18.2 15.4 17.2 16.7 15.1 13.4 13.7 14.2 14.5 16.7
 14.9 13.6 15.8 16.6 18.2 18.2 15.4 13.2 14.9 15.  14.  14.4 20.1 24.8
 13.2 19.2 16.  12.9 14.7 15.5 16.5 20.1 15.8 17.5 15.2 14.4 21.7 19.9
 13.8 18.  11.4 15.1 17.  16.4 12.6 16.9 16.1 19.4 16.  16.2 14.2 14.4
 14.8 20

8. Show how to select the number `99` in the array below. 

In [46]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [47]:
#select number 99 in the array
print("Number 99: ", select_99[1,2])

Number 99:  99


9. Select the last element in each subarray (do this with one operation.)

In [61]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [65]:
#select a particular column - in this case last column
print(select_more[:,2])

[3 6 9]


10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [6]:
# will return the functions for the the argument 'log' which is a string, and it can be in the form of a function name
#or anything related to it.
np.lookfor('log')

#numpy.log - Natural logarithm, element-wise
print(np.log(mpg))

#numpy.log2 - Base-2 logarithm of 'x'
print(np.log2(mpg))

#numpy.log10 - Return the base 10 logarithm of the input array, element wise
print(np.log10(mpg))


Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [7]:
#Unique items in Origin
#np.unique(origin)
print("Unique items in origin: " , np.unique(origin))


Unique items in origin:  ['Europe' 'Japan' 'US']


12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [16]:
#create 2D array
array_2d = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print("2D array: {}  \n Dimension: {}  \n Shape: {} ".format(array_2d,array_2d.ndim, array_2d.shape))

#create 3D array
array_3d = np.array([[[1,2,3,4],[5,6,7,8,],[9,10,11,12]]])
print("\n3D array: {}  \n Dimension: {}  \n Shape: {} ".format(array_3d,array_3d.ndim, array_3d.shape))

#create 4D array
array_4d = np.array([[[[1,2,3],[5,6,7],[9,10,11]]]])
print("\n4D array: {}  \n Dimension: {}  \n Shape: {} ".format(array_4d,array_4d.ndim, array_4d.shape))


2D array: [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]  
 Dimension: 2  
 Shape: (2, 7) 

3D array: [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]  
 Dimension: 3  
 Shape: (1, 3, 4) 

4D array: [[[[ 1  2  3]
   [ 5  6  7]
   [ 9 10 11]]]]  
 Dimension: 4  
 Shape: (1, 1, 3, 3) 


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [126]:
#Boolean indexing to create an array of True/False for origin = US
boolean_array_US = [origin == 'US']
print("Boolean index array for origin 'US':\n", boolean_array_US)

Boolean index array for origin 'US':
 [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  T

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [19]:
#Cars of US origin
#boolean_array as boolean index for origin = US
#car[boolean_array_US == True]
print("Cars of 'US' origin: \n" , car[boolean_array_US])

Cars of 'US' origin: 
 ['Chevrolet Chevelle Malibu' 'Buick Skylark 320' 'Plymouth Satellite'
 'AMC Rebel SST' 'Ford Torino' 'Ford Galaxie 500' 'Chevrolet Impala'
 'Plymouth Fury iii' 'Pontiac Catalina' 'AMC Ambassador DPL'
 'Chevrolet Chevelle Concours (sw)' 'Ford Torino (sw)'
 'Plymouth Satellite (sw)' 'AMC Rebel SST (sw)' 'Dodge Challenger SE'
 "Plymouth 'Cuda 340" 'Ford Mustang Boss 302' 'Chevrolet Monte Carlo'
 'Buick Estate Wagon (sw)' 'Plymouth Duster' 'AMC Hornet' 'Ford Maverick'
 'AMC Gremlin' 'Ford F250' 'Chevy C20' 'Dodge D200' 'Hi 1200D'
 'Chevrolet Vega 2300' 'Ford Pinto' 'AMC Gremlin'
 'Plymouth Satellite Custom' 'Chevrolet Chevelle Malibu' 'Ford Torino 500'
 'AMC Matador' 'Chevrolet Impala' 'Pontiac Catalina Brougham'
 'Ford Galaxie 500' 'Plymouth Fury iii' 'Dodge Monaco (sw)'
 'Ford Country Squire (sw)' 'Pontiac Safari (sw)'
 'AMC Hornet Sportabout (sw)' 'Chevrolet Vega (sw)' 'Pontiac Firebird'
 'Ford Mustang' 'Mercury Capri 2000' 'Plymouth Cricket'
 'Dodge Colt Hardtop'

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [99]:
#An identity matrix is a square matrix in which all the elements of principal diagonals are one, and all other elements 
#are zeros. If any matrix is multiplied with the identity matrix, the result will be given matrix.

#Create identity matrix of size 5
id_matrix = np.identity(5)
print("Identity matrix of size 5: \n", id_matrix)

Identity matrix of size 5: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


2. Transpose the following array. 

In [22]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


In [23]:
#transpose array
print("Transposed array :\n ", transpose_me.transpose())

Transposed array :
  [[1 4 7]
 [2 5 8]
 [3 6 9]]


3. Why does this multiplication operation fail? 

In [118]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
# The multiplication operation will fail because the shape of the two arrays are not compatible for multiplication.
# shape of arr1 is  (3,3)
# shape of arr2 is (2,3)

#Multiplication with arr2 of shape (1,3) or (3,3) will work
# arr2 = np.array([1,2,3]) -> i.e shape(1,3)
# arr1 * arr2 will give array([[ 1,  4,  9],
       #[ 4, 10, 18],
       #[ 7, 16, 27]])

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [103]:
europe_cars_hp = horsepower[origin == 'Europe']
avg_europe_cars = np.mean(europe_cars_hp)
print("Average of horsepower of Europe cars: ", avg_europe_cars )

Average of horsepower of Europe cars:  78.78082191780823


5. On average are Japanse cars more fuel efficient than US cars? 

In [115]:
us_cars_mpg = mpg[origin == 'US']
avg_us_cars_mpg = np.mean(us_cars_mpg)
print("Average of mpg of US cars: ", avg_us_cars_mpg )

japan_cars_mpg = mpg[origin == 'Japan']
avg_japan_cars_mpg = np.mean(japan_cars_mpg)
print("Average of mpg of Japan cars: ", avg_japan_cars_mpg )

print("Are japanese cars more fuel effient than US cars ? ", avg_japan_cars_mpg>avg_us_cars_mpg)

Average of mpg of US cars:  19.688188976377955
Average of mpg of Japan cars:  30.450632911392404
Are japanese cars more fuel effient than US cars ?  True


6. What is the correlation coefficient of `mpg` and `weight`?

In [11]:
#using numpy corrcoef - correlation coefficient function 
print("Correlation coefficient of mpg and weight: \n", np.corrcoef(mpg,weight))

Correlation coefficient of mpg and weight: 
 [[ 1.         -0.78750994]
 [-0.78750994  1.        ]]


7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [ ]:
#Array is fast because it has elements of same data type, compact storage - consumes less memory,
#its stored right next to each other. Arrays are used in Machine learning - Tensors, scientific and numeric computing - Vector, Matrices 
#and Neural network
#Arrays are convenient to use

#List - List are slow. They are not stored right next to each other and consumes more memory. 
#It can have elements of different data types so can be used to work on multiple data types. 
#It can be used as use Stack(LIFO) and Queue(FIFO)