In [30]:
import numpy as np
import pandas as pd

## 1. Write a function that calculates the dot product manually AND a function that calculates the cross product manually. 
- Both should accept two vectors and perform the calculation. Be sure to use try except and error handling for basic issues that might occur


### Dot product 
* a · b = ax × bx + ay × by

In [175]:
#Call numpy dot product and dot_prod function. Including try and except for error handling

try:
    
    north = np.array([0,1])
    east = np.array([1,0])
    south = np.array([0,-1])
    west = np.array([-1,0])

    #Using numpy dot product
    print("Using numpy dot product")
    print(np.dot(np.array([1,2,3]),np.array([1,2,3])))
    print(np.dot(np.array([5,-4]),np.array([-7,2])))
    print(np.dot(north,east))
    print(np.dot(west,east))
    #print(np.dot(np.array([5,-4],[2,6]),np.array([-7,2],[1,6])))

    #Using function dot_prod
    print("Using function dot prod")
    print(dot_prod(np.array([1,2,3]),np.array([1,2,3])))
    print(dot_prod(np.array([5,-4]),np.array([-7,2])))
    print(dot_prod(north,east))
    print(dot_prod(west,east))
    print(dot_prod(np.array([5,-4],[2,6]),np.array([-7,2],[1,6])))
                   
except:
    print("Not valid parameters")


Using numpy dot product
14
-43
0
-1
Using function dot prod
14
-43
0
-1
Not valid parameters


In [165]:
#Function to calculate dot product of vectors
def dot_prod(v1,v2):
        return sum(i*j for (i,j) in zip(v1, v2))
    

### Cross Product
##### Example: The cross product of a = (2,3,4) and b = (5,6,7)
* cx = aybz − azby = 3×7 − 4×6 = −3
* cy = azbx − axbz = 4×5 − 2×7 = 6
* cz = axby − aybx = 2×6 − 3×5 = −3
##### Answer: a × b = (−3,6,−3)

In [176]:
#Call numpy cross product and cross_prod function. Including try and except for error handling

try:
    
    #Using numpy cross product
    print('Using numpy cross product')
    print(np.cross(np.array([5,-4]), np.array([-7,2]), axisa=0, axisb=0))
    print(np.cross(np.array([5,-4,3]), np.array([-7,2,-8]), axisa=0, axisb=0))
    print(np.cross(np.array([2,3,4]), np.array([5,6,7]), axisa=0, axisb=0))
    print(np.cross(np.array([3,5,-7]), np.array([2,-6,4]), axisa=0, axisb=0))
    print(np.cross(north,east))
    print(np.cross(west,east))
    
    #Using function cross_prod
    print('Using function cross_prod')
    print(cross_prod(np.array([5,-4]),np.array([-7,2])))
    print(cross_prod(np.array([5,-4,3]),np.array([-7,2,-8])))
    print(cross_prod(np.array([2,3,4]),np.array([5,6,7])))
    print(cross_prod(np.array([3,5,-7]),np.array([2,-6,4])))
    print(cross_prod(north,east))
    print(cross_prod(west,east))

except:
    print("Not valid parameters")

Using numpy cross product
-18
[ 26  19 -18]
[-3  6 -3]
[-22 -26 -28]
-1
0
Using function cross_prod
-18
[ 26  19 -18]
[-3  6 -3]
[-22 -26 -28]
-1
0


In [169]:
#Function to calculate cross product of vectors
def cross_prod(v1,v2):
    result = 0
    x=0
    y=1
    z=2
    if v1.shape[0] == 3 :
        cx = (v1[y]*v2[z]) - (v1[z]*v2[y])
        cy = (v1[z]*v2[x]) - (v1[x]*v2[z])
        cz = (v1[x]*v2[y]) - (v1[y]*v2[x])

        result = np.array([cx,cy,cz])
        
    if v1.shape[0] == 2:
        cx = (v1[x]*v2[y]) - (v1[y]*v2[x])
        result = cx
        
    return result

In [ ]:
#2. In a markdown section in your notebook, explain what one hot encoding is and why we use it. 
# Then, manually calculate a one hot encoding for the Belize_Airbnb_listings.csv
# neighborhood_group column. Note: manually means don’t use scikitlearn or keras

## 2. What is one hot encoding?
* One hot encoding is representing categorical values into binary values(0/1). When using machine algorithms, the categorical values(which are string) can not be processed and hence needs to be converted to numerical values. If we just assign a numerical value like 1,2,3.. then machine can interprete it as one value is greater or less than the other. Hence, it needs to be one hot encoded to be processed by algorithm.


In [177]:
belize_airbnb_df = pd.read_csv("belize_airbnb_listings.csv")
belize_airbnb_df.head(1)

id                                        name  host_id host_name  \
0  36666  Mo's Cozy Casa w/ veranda & access to dock   157752   Monique   

  neighbourhood_group   neighbourhood  latitude  longitude        room_type  \
0              Belize  Belize Islands  17.74786  -88.02398  Entire home/apt   

   price  minimum_nights  number_of_reviews last_review  reviews_per_month  \
0    141               3                250   2/23/2021                2.0   

   calculated_host_listings_count  availability_365  
0                               5               225

In [180]:
#One hot encoding for neighbourhood_group column of dataframe
# Using .loc
belize_hotencoded_df = belize_airbnb_df

belize_hotencoded_df['Belize'] = 0
belize_hotencoded_df['Stann Creek'] = 0
belize_hotencoded_df['Cayo'] = 0
belize_hotencoded_df['Toledo'] = 0
belize_hotencoded_df['Corozal'] = 0
belize_hotencoded_df['Orange Walk'] = 0

belize_hotencoded_df.loc[belize_hotencoded_df["neighbourhood_group"]=="Belize","Belize"] = 1
belize_hotencoded_df.loc[belize_hotencoded_df["neighbourhood_group"]=="Stann Creek","Stann Creek"] = 1
belize_hotencoded_df.loc[belize_hotencoded_df["neighbourhood_group"]=="Cayo","Cayo"] = 1
belize_hotencoded_df.loc[belize_hotencoded_df["neighbourhood_group"]=="Toledo","Toledo"] = 1
belize_hotencoded_df.loc[belize_hotencoded_df["neighbourhood_group"]=="Corozal","Corozal"] = 1
belize_hotencoded_df.loc[belize_hotencoded_df["neighbourhood_group"]=="Orange Walk","Orange Walk"] = 1

belize_hotencoded_df

id                                               name    host_id  \
0        36666         Mo's Cozy Casa w/ veranda & access to dock     157752   
1        36690  Mo's Cozy Cabana w/ comfy veranda & access to ...     157752   
2       108932  Purple House eco solar  w/ ocean & wildlife views     563377   
3       110483                            Michelo's fuchsia suite     567809   
4       120115               Seaside Villas Second Floor Unit  #4     604999   
...        ...                                                ...        ...   
2791  48283996                                     Magical Island   17994012   
2792  48287613   The Luxury Suite - Corozal, Bz- 3Bdr/2bthr CASA1  375769845   
2793  48296096  Lagoon front apartment w/shared pool -  two mi...   76414486   
2794  48296978                          Beachfront Poolside Condo   15308338   
2795  48332221           Standard Room - San Ignacio Resort Hotel   60399527   

          host_name neighbourhood_group         neighbourhood   latitude  \
0           Monique              Belize        Belize Islands  17.747860   
1           Monique              Belize        Belize Islands  17.748320   
2           Michael              Belize        Belize Islands  17.732210   
3            Michel         Stann Creek  Stann Creek Mainland  16.521140   
4             Bobbi              Belize        Belize Islands  17.741660   
...             ...                 ...                   ...        ...   
2791         Ronald              Belize        Belize Islands  17.945690   
2792        Michael             Corozal               Corozal  18.374630   
2793  Vacasa Belize              Belize        Belize Islands  17.934580   
2794      Alexandra              Belize        Belize Islands  17.930010   
2795    San Ignacio                Cayo                  Cayo  17.154127   

      longitude        room_type  price  ...  last_review  reviews_per_month  \
0    -88.023980  Entire home/apt    141  ...    2/23/2021               2.00   
1    -88.024740  Entire home/apt     71  ...    2/19/2021               2.46   
2    -88.038240  Entire home/apt    191  ...    3/14/2020               0.78   
3    -88.369260       Hotel room    121  ...    2/24/2020               0.29   
4    -88.023950  Entire home/apt    343  ...    3/18/2020               0.64   
...         ...              ...    ...  ...          ...                ...   
2791 -87.944620  Entire home/apt   1054  ...          NaN                NaN   
2792 -88.400190  Entire home/apt    401  ...          NaN                NaN   
2793 -87.955220  Entire home/apt    252  ...          NaN                NaN   
2794 -87.957120  Entire home/apt    242  ...          NaN                NaN   
2795 -89.069689     Private room    226  ...          NaN                NaN   

     calculated_host_listings_count  availability_365  Belize  Stann Creek  \
0                                 5               225       1            0   
1                                 5               164       1            0   
2                                 1               364       1            0   
3                                 3               331       0            1   
4                                22               203       1            0   
...                             ...               ...     ...          ...   
2791                              2               347       1            0   
2792                              2               302       0            0   
2793                            204               364       1            0   
2794                              4               364       1            0   
2795                              5               365       0            0   

      Cayo  Toledo  Corozal  Orange Walk  
0        0       0        0            0  
1        0       0        0            0  
2        0       0        0            0  
3        0       0        0            0  
4        0       0       

In [181]:
#One hot encoding for neighbourhood_group column of dataframe
#Using dummies
dummies = pd.get_dummies(belize_airbnb_df.neighbourhood_group)
dummies.head(5)

Belize  Cayo  Corozal  Orange Walk  Stann Creek  Toledo
0       1     0        0            0            0       0
1       1     0        0            0            0       0
2       1     0        0            0            0       0
3       0     0        0            0            1       0
4       1     0        0            0            0       0

In [182]:
merged_hotencoded = pd.concat([belize_airbnb_df,dummies],axis='columns')
merged_hotencoded.head(5)

id                                               name  host_id  \
0   36666         Mo's Cozy Casa w/ veranda & access to dock   157752   
1   36690  Mo's Cozy Cabana w/ comfy veranda & access to ...   157752   
2  108932  Purple House eco solar  w/ ocean & wildlife views   563377   
3  110483                            Michelo's fuchsia suite   567809   
4  120115               Seaside Villas Second Floor Unit  #4   604999   

  host_name neighbourhood_group         neighbourhood  latitude  longitude  \
0   Monique              Belize        Belize Islands  17.74786  -88.02398   
1   Monique              Belize        Belize Islands  17.74832  -88.02474   
2   Michael              Belize        Belize Islands  17.73221  -88.03824   
3    Michel         Stann Creek  Stann Creek Mainland  16.52114  -88.36926   
4     Bobbi              Belize        Belize Islands  17.74166  -88.02395   

         room_type  price  ...  Cayo  Toledo  Corozal  Orange Walk  Belize  \
0  Entire home/apt    141  ...     0       0        0            0       1   
1  Entire home/apt     71  ...     0       0        0            0       1   
2  Entire home/apt    191  ...     0       0        0            0       1   
3       Hotel room    121  ...     0       0        0            0       0   
4  Entire home/apt    343  ...     0       0        0            0       1   

   Cayo  Corozal  Orange Walk  Stann Creek  Toledo  
0     0        0            0            0       0  
1     0        0            0            0       0  
2     0        0            0            0       0  
3     0        0            0            1       0  
4     0        0            0            0       0  

[5 rows x 28 columns]

### Week 10 in class - warm up

In [150]:
#Take the following list [0,1,2,3,4,5,6,7,8,9] and reverse it
#Using sort method
num_list = [0,1,2,3,4,5,6,7,8,9]
num_list.sort(reverse=True)
print(num_list)

#Using slicing
nlist = [0,1,2,3,4,5,6,7,8,9]
print(nlist[::-1])

#Using array sort
narray = np.array([0,1,2,3,4,5,6,7,8,9])
print(-np.sort(-narray))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[9 8 7 6 5 4 3 2 1 0]


In [151]:
#Write a list comprehension to take the reversed list and divide each value by 2
print(num_list)
divideby_2 = [x/2 for x in num_list]
print(divideby_2)

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[4.5, 4.0, 3.5, 3.0, 2.5, 2.0, 1.5, 1.0, 0.5, 0.0]
